### ISSUE TITLE
Command + E and nothing happens

### ISSUE THREAD

**Issue by Simcat** [tisho/sketch-plugins#25]
Not working. OSX 10.9.5
Sketch Version 3.2.2

![screen shot 2015-01-13 at 3 50 07 pm](https://cloud.githubusercontent.com/assets/1505159/5731735/f101b8ec-9b3b-11e4-971e-c7950b4f639b.png)

**Comment by Nitive** [comment]
Not working too.
OS X 10.10
Sketch 3.2.1 and Sketch 3.2.2
![sketch error](https://cloud.githubusercontent.com/assets/6770225/6315105/2dddeb5e-ba19-11e4-8774-54d437c2de73.gif)

**Comment by tisho** [comment]
The plugin isn't compatible with Sketch 3, because Sketch 3 already has symbols built into the app.

**Comment by Simcat** [comment]
Thanks
